branch-defaults:
  default:
    environment: TwittMap-dev
global:
  application_name: TwittMap
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4
  default_region: us-west-2
  profile: null
  repository: null
  sc: null
